name: 'Deploy progress'
description: 'Deploy Progress'
author: 'Philip Sabri'
inputs:
  gcp_key:
    description: 'desc'
    required: true
  name:
    description: 'desc'
    required: true
  tag:
    description: 'desc'
    required: true
  image:
    description: 'desc'
    required: true
  cluster_name:
    description: 'desc'
    required: true
  cluster_zone:
    description: 'desc'
    required: true
  cluster_project:
    description: 'desc'
    required: true
runs:
  using: 'docker'
  image: 'docker://gcr.io/gloot-automation/infra-gitops-deploy:0.0.1-beta.5'
  args:
    - ${{ inputs.gcp_key }}
    - ${{ inputs.name }}
    - ${{ inputs.tag }}
    - ${{ inputs.image }}
    - ${{ inputs.cluster_name }}
    - ${{ inputs.cluster_zone }}
    - ${{ inputs.cluster_project }}
