name: "Deploy progress"
description: "Deploy Progress"
author: "Philip Sabri"
inputs:
  gcp_key:
    description: "GCP Service account key"
    required: true
  name:
    description: "Name of serivce"
    required: true
  tag:
    description: "Image tag"
    required: true
  image:
    description: "Full image name with registry"
    required: true
  cluster_name:
    description: "Name of the cluster"
    required: true
  cluster_zone:
    description: "Name of the zone the cluster is deployed to"
    required: true
  cluster_project:
    description: "Name of the project the cluster is deployed to"
    required: true
  namespace:
    default: "default"
    description: "Namespace of service"
    required: true
  canary:
    default: "false"
    description: "Set to true if canary deployments are used"
    required: true
runs:
  using: "docker"
  image: "docker://gcr.io/gloot-automation/infra-gitops-deploy:latest"
  args:
    - ${{ inputs.gcp_key }}
    - ${{ inputs.name }}
    - ${{ inputs.tag }}
    - ${{ inputs.image }}
    - ${{ inputs.cluster_name }}
    - ${{ inputs.cluster_zone }}
    - ${{ inputs.cluster_project }}
    - ${{ inputs.namespace }}
    - ${{ inputs.canary }}
