name: "Deploy progress"
description: "Deploy Progress"
author: "Philip Sabri"
inputs:
  gcp_key:
    description: "GCP Service account key"
    required: true
  name:
    description: "Name of serivce"
    required: true
  tag:
    description: "Image tag"
    required: true
  image:
    description: "Full image name with registry"
    required: true
  namespace:
    default: "default"
    description: "Namespace of service"
    required: true
  canary:
    default: "false"
    description: "Set to true if canary deployments are used"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.gcp_key }}
    - ${{ inputs.name }}
    - ${{ inputs.tag }}
    - ${{ inputs.image }}
    - ${{ inputs.namespace }}
    - ${{ inputs.canary }}
