name: Build & Push image

on: push

jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    name: Build and push docker image
    env:
      DOCKER_IMAGE_GCR: eu.gcr.io/gloot-automation/infra-gitops-deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
    - run: gcloud auth configure-docker
    - name: Bump version and push tag
      id: version_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "main"
    - name: Build & push image to GCR
      run: |
        docker build . -t $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }}
        docker push $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }}
    # Update 'latest' image if on main branch
    - name: Push and update latest image in GCR
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }} $DOCKER_IMAGE_GCR:latest
        docker push $DOCKER_IMAGE_GCR:latest
